AgriBioHVC/urls.py
"""
AgriBioHVC (Top-level) URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin as djadmin
from django.views.generic.base import RedirectView

import common.views
import efpbrowser.urls
import degustbrowser.urls
#import geneview.urls
import landing.urls
import ptadmin.urls
import background.urls
from AgriBioHVC import settings

urlpatterns = [
    
    url(r'^efp/', include(efpbrowser.urls, namespace='efp')),
    url(r'^degust/', include(degustbrowser.urls, namespace='degust')),
    url(r'^portal-admin/', include(ptadmin.urls, namespace='ptadmin')),
    url(r'^portal-admin$', RedirectView.as_view(url='portal-admin/', permanent=False)),
    url(r'^background/', include(background.urls, namespace='background')),
    
    url(r'^django-admin/', djadmin.site.urls),
    url(r'^django-admin$', RedirectView.as_view(url='django-admin/', permanent=False)),
    
    url(r'^login', common.views.login_user, name='login'),
    url(r'^logout', common.views.logout_user, name='logout'),
    
    url(r'^content/([^/]*)', common.views.content, name='content'),
    url(settings.DATA_URL, common.views.data_server, name='content'),
    
    url(r'^status', common.views.status, name='status'),
]
urlpatterns.extend(landing.urls.urlpatterns)

landing/urls.py
"""
Landing portal URL Configuration

NOTE: these urlpatterns are appended to end of master URLs so they are 
      effectively top-level URLs too.
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

import landing.views

from common.uid import ORGANISMUID, COLLECTIONUID, DATASETUID, SAMPLEUID, FEATUREUID

urlpatterns = [
    
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')?)$', landing.views.home, name='home'),
    
    # /[COLLECTIONUID/]dataset/ORGANISMUID/DATASETUID/SAMPLEUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')$', landing.views.datasetlist, name='datasetlist'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')$', landing.views.datasetdetails, name='datasetdetails'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')/(?P<sampleuid>'+SAMPLEUID+r')$', landing.views.sampledetails, name='sampledetails'),
    
    # /download/DATASETUID/FORMAT
    url(r'^download/('+DATASETUID+r')/([a-z]+)$', landing.views.datasetdownload, name='datasetdownload'),
    
    # /feature/DATASETUID/FEATUREUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?feature/(?P<datasetuid>'+DATASETUID+r')/(?P<featureuid>'+FEATUREUID+r')$', landing.views.datasetfeature, name='datasetfeature'),
    
    # /reference/REFERENCEUID[/FEATUREUID]
#     url(r'^reference$', landing.views.referencelist, name='referencelist'),
#     url(r'^reference/('+REFERENCEUID+r')$', landing.views.referencedetails, name='referencedetails'),
#     url(r'^reference/('+REFERENCEUID+r')/('+FEATUREUID+r')$', landing.views.referencegene, name='referencegene'),
    
    url(r'^help', RedirectView.as_view(url='https://docs.google.com/document/d/1o7IyQp02bsBW_FZDo6RFzSHD34aG_wJuhuvBYFv2GLc', permanent=False)),

]

ptadmin/urls.py
"""
Admin portal URL Configuration

Namespace: 'ptadmin'
"""
from django.conf.urls import url

import ptadmin.views.dataset
import ptadmin.views.organism
import ptadmin.views.system
import ptadmin.views.template
import ptadmin.views.usergroup

from common.uid import ORGANISMUID, DATASETUID, REFERENCEUID

urlpatterns = [
    
    url(r'^$', ptadmin.views.dataset.home, name='home'),
    
    # /dataset/DATASETUID/*
    url(r'^dataset$', ptadmin.views.dataset.list, name='listdataset'),
    url(r'^dataset/new$', ptadmin.views.dataset.newdataset, name='newdataset'),
    url(r'^dataset/('+DATASETUID+r')/upload$', ptadmin.views.dataset.upload, name='uploaddataset'),
    url(r'^dataset/('+DATASETUID+r')/edit$', ptadmin.views.dataset.edit, name='editdataset'),
    url(r'^dataset/('+DATASETUID+r')/efpimage$', ptadmin.views.dataset.efpimage, name='efpimage'),
    url(r'^dataset/('+DATASETUID+r')/deployefp$', ptadmin.views.dataset.deployefp, name='deployefp'),
    url(r'^dataset/('+DATASETUID+r')/deploydegust$', ptadmin.views.dataset.deploydegust, name='deploydegust'),
    
    # /organism/ORGANISMUID
    url(r'^organism$', ptadmin.views.organism.listOrganism, name='listorganism'),
    url(r'^organism/add$', ptadmin.views.organism.addOrganism, name='organismadd'),
    url(r'^organism/add-old$', ptadmin.views.organism.addOrganism, name='speciesadd'), # deprecated
    url(r'^organism/('+ORGANISMUID+r')$', ptadmin.views.organism.detailOrganism, name='detailorganism'),
    
    # /organism/ORGANISMUID/reference/REFERENCEUID/*
    url(r'^organism/('+ORGANISMUID+r')/reference/add$', ptadmin.views.organism.addReference, name='referenceadd'),
    url(r'^organism/('+ORGANISMUID+r')/reference/('+REFERENCEUID+r')/upload$', ptadmin.views.organism.uploadReferenceFeatures, name='referenceupload'),
    url(r'^organism/('+ORGANISMUID+r')/reference/('+REFERENCEUID+r')/deployefp$', ptadmin.views.organism.deployreferenceefp, name='deployreferenceefp'),
    url(r'^organism/('+ORGANISMUID+r')/reference/('+REFERENCEUID+r')/deploylanding$', ptadmin.views.organism.deployreferencelanding, name='deployreferencelanding'),
    
    url(r'^group$', ptadmin.views.usergroup.listgroup, name='listgroup'),
    url(r'^group/new$', ptadmin.views.usergroup.newgroup, name='newgroup'),
    url(r'^user/new$', ptadmin.views.usergroup.newuser, name='newuser'),
    url(r'^group/([0-9]+)/addusers$', ptadmin.views.usergroup.addusergroup, name='addusergroup'),
    url(r'^group/([0-9]+)/removeuser/([0-9]+)$', ptadmin.views.usergroup.removeusergroup, name='removeusergroup'),
    
    url(r'^view-template$', ptadmin.views.template.viewTemplate, name='viewTemplate'),
    url(r'^update-template$', ptadmin.views.template.updateTemplate, name='updateTemplate'),
    
    url(r'^colour-chart$', ptadmin.views.dataset.colourChart, name='colourChart'),
    
    url(r'^system/status$', ptadmin.views.system.status, name='systemstatus'),
#     url(r'^view$', ptadmin.views.view, name='view'),
#     url(r'^.*$', RedirectView.as_view(pattern_name='home', permanent=False)),
]

common/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Group
from django.utils import timezone

from common import modelfields



class Species(models.Model):
    '''Each species represented in database'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL.  e.g. barley')
    name = models.CharField(max_length=100, help_text='User pointing name for species.  e.g. Barley')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above data-set list on the Species landing page')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below data-set list on the Species landing page')
    
    # system fields
    public_dataset_count = models.IntegerField(default=0, help_text='Automatically updated by Dataset model.  Displayed on homepage')
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "Organism: %s [/%s]" % (self.name, self.uid)
    
    def references(self):
        return self.reference_set.filter(deleted__isnull=True)

REFERENCE_TYPE_CHOICES = (
    ('ge','Genome'),
    ('dg','Draft Genome'),
    ('tr','Transcriptome'),
    ('dt','Draft Transcriptome'),
    ('st','Self-assembled Transcriptome'),
)
REFERENCE_TYPE_LOOKUP = dict(REFERENCE_TYPE_CHOICES)

# REFERENCE_FEATURES_CHOICES = (
#     ('gene','Genes'),
#     ('tran','Transcripts'),
# )
# REFERENCE_FEATURES_LOOKUP = dict(REFERENCE_FEATURES_CHOICES)

class Reference(models.Model):
    '''A reference genome for a Species'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL and efp database table name.  e.g. barley')
    name = models.CharField(max_length=100, help_text='User pointing name for reference.  e.g. Barley')
    type = models.CharField(max_length=50, blank=True, help_text='Type of reference genome/transcriptome', choices=REFERENCE_TYPE_CHOICES)
    description = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text describing this reference e.g. where it was sourced, changes etc.')
    description_footer = models.TextField(null=True, blank=True, help_text='Extra Markdown/HTML formatted text describing this reference (below data-set list)')
    featurefile = models.CharField(max_length=56, blank=True, help_text='The name of the feature file (as saved in upload dir)', )
#     gfffeatures = modelfields.MultiCharField(max_length=20, blank=True, null=True, help_text='The types of features to include in reference', choices=REFERENCE_FEATURES_CHOICES)
    
    species = models.ForeignKey(Species)
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "Reference: %s [%s]" % (self.name, self.species.name)


class ReferenceFeature(models.Model):
    '''Transcript details for describing gene on landing page'''
     
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL and efp database table name.  e.g. barley')
    name = models.CharField(max_length=100, null=True, blank=True, help_text='User friendly name for feature if available')
    description = models.TextField(null=True, blank=True, help_text='Extra annotation for the gene/transcript/feature')
    
    reference = models.ForeignKey(Reference)
    
#     created = models.DateTimeField(auto_now_add=True)
#     modified = models.DateTimeField(auto_now=True)
#     deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")
    
    def __str__(self):
        if self.name:
            return "%s (%s)" % (self.name, self.uid)
        return self.uid


class Collection(models.Model):
    '''Group of data-sets'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL, file-system and database.  Restrict to [._a-zA-Z0-9].  e.g. smith2017')
    name = models.CharField(max_length=100, help_text='User pointing name for Collection.  e.g. AgriConnect, La Trobe etc.')
    name_short = models.CharField(max_length=50, null=True, blank=True, default=None, help_text='User pointing name used in breadcrumbs.  e.g. AgriConnect, La Trobe etc.')
    description_short = models.CharField(max_length=250, null=True, blank=True, help_text='Plain text formatted text for inclusion on home-page with collection link')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above data-sets')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below data-sets')

    template = models.ForeignKey('UpdateableTemplate', help_text='The template to use to draw landing page / viewers within')
    link_ltu = models.BooleanField(default=True, help_text='Link to the La Trobe pages in landing portal pages')
    link_top = models.BooleanField(default=True, help_text='Link to the top level landing portal page in landing portal pages, i.e. page selecting collection')
    link_collection = models.BooleanField(default=True, help_text='Include this collection on list of collections on landing home-page')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "%s [/%s]" % (self.name, self.uid)
    
    def get_name_short(self):
        if self.name_short:
            return self.name_short
        return self.name
    def get_template(self):
        if self.template:
            return "UPDATEABLE_%s" % (self.template.name,)
        return None


COUNT_FORMAT_CHOICES = (
    ('RAW','Raw counts'),
    ('RPKM','RPKM/FPKM normalised counts'),
    ('TPM','TPM normalised counts'),
)
COUNT_FORMAT_LOOKUP = dict(COUNT_FORMAT_CHOICES)


class Dataset(models.Model):
    '''Each dataset represented in database'''
    
    class Meta:
        permissions = (
            ("can_view_any_dataset", "View Any Dataset"),
            ("can_edit_any_dataset", "Edit Any Dataset"),
        )
    
    # basic details
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL, file-system and database.  Restrict to [a-z0-9].  e.g. smith2017')
    name = models.CharField(max_length=100, help_text='User pointing name for Dataset.  e.g. Barley germination')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above samples on data-set details')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below samples on data-set details')
    
    # file uploads
    countsfile = models.CharField(max_length=50, blank=True, help_text='The name of the counts file (as saved in upload dir)', )
    countsformat = models.CharField(max_length=5, blank=True, help_text='The type of counts in counts file', choices=COUNT_FORMAT_CHOICES)
    efphomeimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file used on homescreen i.e. without any expression. (as saved in upload dir)')
    efpexprimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file user to show expression (as saved in upload dir)')
    efpdownimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file user to show expression on download (as saved in upload dir)')
    countsdownload = models.BooleanField(default=False, blank=True, help_text='Check to allow users to download counts file')
    
    # detailed settings
    publish = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to publish this dataset (publicly).  If in future it will automatically publish after this date.")
    labgroup = models.ForeignKey(Group, blank=True, null=True, help_text="The group of users who can access this dataset regardless if it's published")
    collections = models.ManyToManyField(Collection, blank=True, help_text='List of collections this data-set should be included in')
    metadata = models.TextField(blank=True, help_text='JSON formatted object representing the metadata of this dataset')
    
    externallinkurl = models.CharField(max_length=500, blank=True, help_text='URL to use for external link, GENEID is replaced with actual gene id', )
    externallinklabel = models.CharField(max_length=50, blank=True, help_text='Text label to use for external link, GENEID is replaced with actual gene id', )
    externallinkregex = models.CharField(max_length=100, blank=True, help_text='Regular expression used to select part of geneid to use in external link. e.g. remove transcript number', )
    externallinksub = models.CharField(max_length=50, blank=True, help_text='Substitution string used with regular expression e.g. remove transcript number', )
    
    species = models.ForeignKey(Species, blank=True, null=True, help_text='Organism of samples')
    reference = models.ForeignKey(Reference, default=None, blank=True, null=True, help_text='Reference used during mapping.  Data-set IDs must match reference IDs.')
    
    idcolumn = models.CharField(max_length=100, blank=True, null=True, help_text='The column in data-set which represents the gene/transcript ID.  This must match IDs used in reference.')

ptadmin/views/system.py
'''
Created on 11Jul.,2017

@author: arobinson
'''

import subprocess

from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
try:
    from django.template.context_processors import csrf
except:
    from django.core.context_processors import csrf

from AgriBioHVC import settings
from common.bl.messagemanager import MessageManager

@permission_required('ptadmin.view_portal')
def status(request):
    '''Renders a status page'''
    
    # lookup disk usage
    cmd = ['df', '-h']
    cmd.extend(settings.DISK_USAGE_MOUNTS)
    usage_string = subprocess.check_output(cmd)
    usage = []
    for line in usage_string.split('\n')[1:]:
        if line:
            cols = line.split()
            usageint = int(cols[4][:-1])
            status = "OK"
            if usageint >= 90:
                status = "ERROR"
            elif usageint >= 75:
                status = "WARNING" 
            cols.append(status)
            usage.append(cols)
        
    
    # prepare response
    params = {
              'request': request, 
              'messages': MessageManager.getMessages(request),
              'group': 'ptadmin', 
              'page': 'home', 
              'settings': settings,
              'usage': usage,
              'title': 'Portal administration',
             }
    params.update(csrf(request))
    
    return render(request, "portaladmin/status.html", params)

ptadmin/templates/portaladmin/dataset-list.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load stringutils %}
{% load landing %}

{% block 'breadcrumbs' %} > <a href="{% url 'ptadmin:home' %}">Portal Admin</a> > Data-sets{% endblock %}

{% block 'content' %}
	<h1>Data-sets</h1>
	{% rendermessages messages %}
	
	<p><a class="btn btn-default" href="{% url 'ptadmin:newdataset' %}">Add Dataset</a> <a class="btn btn-default" href="{% url 'ptadmin:colourChart' %}">eFP Colour-chart</a></p>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Lab Group</th>
				<th>Organism</th>
				<th># Samples</th>
				<th>Access</th>
				<th>Links</th>
			</tr>
		</thead>
		<tbody>{% for d in datasets %}
			<tr>
				<td>{{d.name|maxlen:50}}</td>
				<td>{{d.labgroup.name}}</td>
				<td>{% if d.species %}<a href="{% url 'datasetlist' d.species.uid %}">{{d.species.name}}</a>{% else %}--{% endif %}</td>
				<td>{{d.samplecount}}</td>
				<td>{% if d.publish is None %}Private{% elif d.publish|future %}Embargo (until {{d.publish}}){% else %}Public{% endif %}</td>
				<td>
					{% if d.species %}<a href="{% url 'datasetdetails' d.species.uid d.uid %}" title="View">[V]</a>{% else %}<span title="Not viewable">[V]</span>{% endif %}
					<a href="{% url 'ptadmin:uploaddataset' d.uid %}" title="Re-upload data">[U]</a>
					<a href="{% url 'ptadmin:editdataset' d.uid %}" title="Edit">[E]</a>
					<a href="{% url 'ptadmin:deployefp' d.uid %}" title="Deploy to eFP">[> eFP]</a><a href="{% url 'ptadmin:deployefp' d.uid %}?s=true" title="Deploy ONLY SETTINGS to eFP">**</a>
					<a href="{% url 'ptadmin:deploydegust' d.uid %}" title="Deploy to Degust">[> Degust]</a>
				</td>
			</tr>{% empty %}
			<tr>
				<td colspan="6">No data-sets in database yet</td>
			</tr>{% endfor %}
		</tbody>
	</table>
{% endblock %}

ptadmin/templates/portaladmin/dataset-upload.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load stringutils %}

{% block 'breadcrumbs' %} > <a href="{% url 'ptadmin:home' %}">Portal Admin</a> > <a href="{% url 'ptadmin:listdataset' %}">Data-sets</a> > Upload{% endblock %}

{% block 'content' %}
			<h1>Data-set Upload</h1>
{% rendermessages messages %}
		
			<form action="{% url 'ptadmin:uploaddataset' dataset.uid %}" method="post" enctype="multipart/form-data" class="form-horizontal">
			    {% csrf_token %}

	    		<div class="form-group">
	    			<label class="col-sm-2 control-label">Data-set</label>
	    			<div class="textonly-row col-sm-6">{{dataset.name}} ({{dataset.uid}})</div>
	    		</div>

			    {{ form.as_bootstrap }}
					    
			    <div class="form-group">
			    	<div class="col-sm-offset-2 col-sm-2">
			    		<input type="submit" class="btn btn-success btn-block" value="Upload" />
			    	</div>
			    </div>
			</form>
{% endblock %}

ptadmin/templates/portaladmin/group-list.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load static from staticfiles %}
{% load stringutils %}
{% load landing %}

{% block 'breadcrumbs' %} > <a href="{% url 'ptadmin:home' %}">Portal Admin</a> > User Groups{% endblock %}

{% block 'content' %}
	<h1>Groups</h1>
	{% rendermessages messages %}
	
	<p>Use this section to add users / groups and edit user-group membership.  Each data-set is 
		owned by a lab-group; all users in this lab-group can view the data-set even if it is 
		private</p>
	
	<p><a class="btn btn-default" href="{% url 'ptadmin:newgroup' %}">Add Group</a> <a class="btn btn-default" href="{% url 'ptadmin:newuser' %}">Add User</a></p>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th># Data-sets</th>
				<th>Users</th>
			</tr>
		</thead>
		<tbody>{% for g in groups %}
			<tr>
				<td>{{g.name}}</a></td>
				<td>{{g.dataset_set|notdeleted|count}}</td>
				<td>
					<ul>{% for u in g.user_set.all %}
						<li>{{u.get_full_name}} <a href="{% url 'ptadmin:removeusergroup' g.id u.id %}" title="Remove {{u.first_name}} from {{g.name}} group"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a></li>{% endfor %}
						<li><a href="{% url 'ptadmin:addusergroup' g.id %}" title="Add user(s) to {{g.name}} group"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
					</ul>
				</td>
			</tr>{% empty %}
			<tr>
				<td colspan="6">No groups in database yet</td>
			</tr>{% endfor %}
		</tbody>
	</table>
{% endblock %}

ptadmin/templates/portaladmin/home.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load stringutils %}
{% load landing %}

{% block 'title' %}
	<title>Portal Admin{% if settings.PORTAL_NAME %} - {{settings.PORTAL_NAME}}{% endif %}</title>
{% endblock %}

{% block 'breadcrumbs' %} > Portal Admin{% endblock %}

{% block 'content' %}
	<h1>Portal Administration</h1>
	{% rendermessages messages %}
	
	<p>Use the buttons below to select the relevant section</p>
	
	<div class="row">
		<div class="col-md-3 large-btn-row"><a class="btn btn-default btn-lg btn-block" href="{% url 'ptadmin:listorganism' %}">Organism</a></div>
		<div class="col-md-6 large-btn-row"><p>Add / Edit Organisms and their references</p></div>
	</div>
	<div class="row">
		<div class="col-md-3 large-btn-row"><a class="btn btn-default btn-lg btn-block" href="{% url 'ptadmin:listdataset' %}">Data-set</a></div>
		<div class="col-md-6 large-btn-row"><p>Add / Edit Data-sets and deploy them to viewers</p></div>
	</div>
	<div class="row">
		<div class="col-md-3 large-btn-row"><a class="btn btn-default btn-lg btn-block" href="{% url 'ptadmin:viewTemplate' %}">Template</a></div>
		<div class="col-md-6 large-btn-row"><p>View / Update landing portal style template</p></div>
	</div>
	<div class="row">
		<div class="col-md-3 large-btn-row"><a class="btn btn-default btn-lg btn-block" href="{% url 'ptadmin:listgroup' %}">User / Group</a></div>
		<div class="col-md-6 large-btn-row"><p>Add / Edit Users and Lab Groups</p></div>
	</div>
	<div class="row">
		<div class="col-md-3 large-btn-row"><a class="btn btn-default btn-lg btn-block" href="{% url 'ptadmin:systemstatus' %}">System</a></div>
		<div class="col-md-6 large-btn-row"><p>Check System status</p></div>
	</div>

{% endblock %}

ptadmin/templates/portaladmin/organism-list.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load stringutils %}
{% load landing %}

{% block 'breadcrumbs' %} > <a href="{% url 'ptadmin:home' %}">Portal Admin</a> > Organisms{% endblock %}

{% block 'content' %}
	<h1>Organisms</h1>
	{% rendermessages messages %}
	
	<p><a class="btn btn-default" href="{% url 'ptadmin:organismadd' %}">Add Organism</a></p>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th># References</th>
				<th># Data-sets</th>
				<th>Links</th>
			</tr>
		</thead>
		<tbody>{% for o in organisms %}
			<tr>
				<td><a href="{% url 'ptadmin:detailorganism' o.uid %}" title="View organism '{{o.name}}'">{{o.name|maxlen:50}}</a></td>
				<td>{{o.reference_set|notdeleted|count}}</td>
				<td>{{o.dataset_set|notdeleted|count}}</td>
				<td>
					<a href="{% url 'ptadmin:detailorganism' o.uid %}" title="View organism '{{o.name}}'">[V]</a>
				</td>
			</tr>{% empty %}
			<tr>
				<td colspan="6">No organisms in database yet</td>
			</tr>{% endfor %}
		</tbody>
	</table>
{% endblock %}

ptadmin/templates/portaladmin/reference-add.html
{% extends 'portaladmin/_base.html' %}

{% load messages %}
{% load dateutils %}
{% load stringutils %}

{% block 'breadcrumbs' %} > <a href="{% url 'ptadmin:home' %}">Portal Admin</a> > 
	<a href="{% url 'ptadmin:listorganism' %}">Organisms</a> > 
	<a href="{% url 'ptadmin:detailorganism' organism.uid %}">{{organism.name}}</a> > 
	New Reference
{% endblock %}

{% block 'content' %}
			<h1>New Reference</h1>
{% rendermessages messages %}
		
			<form action="{% url 'ptadmin:referenceadd' organism.uid %}" method="post" class="form-horizontal">
			    {% csrf_token %}

	    		<div class="form-group">
	    			<label class="col-sm-2 control-label">Organism</label>
	    			<div class="textonly-row col-sm-10">{{organism.name}}</div>
	    		</div>
	    
			    {{ form.as_bootstrap }}
			    
			    <div class="form-group">
			    	<div class="col-sm-offset-2 col-sm-2">
			    		<input type="submit" class="btn btn-success btn-block" value="Add" />
			    	</div>
			    </div>
			</form>
{% endblock %}