AgriBioHVC/urls.py
"""
AgriBioHVC (Top-level) URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin as djadmin
from django.views.generic.base import RedirectView

import common.views
import efpbrowser.urls
import degustbrowser.urls
#import geneview.urls
import landing.urls
import ptadmin.urls
import background.urls
from AgriBioHVC import settings

urlpatterns = [
    
    url(r'^efp/', include(efpbrowser.urls, namespace='efp')),
    url(r'^degust/', include(degustbrowser.urls, namespace='degust')),
    url(r'^portal-admin/', include(ptadmin.urls, namespace='ptadmin')),
    url(r'^portal-admin$', RedirectView.as_view(url='portal-admin/', permanent=False)),
    url(r'^background/', include(background.urls, namespace='background')),
    
    url(r'^django-admin/', djadmin.site.urls),
    url(r'^django-admin$', RedirectView.as_view(url='django-admin/', permanent=False)),
    
    url(r'^login', common.views.login_user, name='login'),
    url(r'^logout', common.views.logout_user, name='logout'),
    
    url(r'^content/([^/]*)', common.views.content, name='content'),
    url(settings.DATA_URL, common.views.data_server, name='content'),
    
    url(r'^status', common.views.status, name='status'),
]
urlpatterns.extend(landing.urls.urlpatterns)

degustbrowser/urls.py
"""
Landing portal URL Configuration

Namespace: degust
"""
from django.conf.urls import url

import degustbrowser.views

from common.uid import COLLECTIONUID, ORGANISMUID, DATASETUID

urlpatterns = [
    
    # /ORGANISMUID/DATASETUID/*
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')/$', degustbrowser.views.home, name='home'),
    url(r'^('+ORGANISMUID+r')/('+DATASETUID+r')/compare.html$', degustbrowser.views.compare, name='compare'),
    url(r'^('+ORGANISMUID+r')/('+DATASETUID+r')/r-json.cgi$', degustbrowser.views.rjson, name='r-json'),
    
    # /ORGANISMUID/DATASETUID/FILENAME
    url(r'^'+ORGANISMUID+r'/'+DATASETUID+r'/(css/[a-z]+.css)$', degustbrowser.views.static, name='staticcss'),
    url(r'^'+ORGANISMUID+r'/'+DATASETUID+r'/([a-z]+.js)$', degustbrowser.views.static, name='staticjs'),
    url(r'^'+ORGANISMUID+r'/'+DATASETUID+r'/(images/[-a-z]+.[pngif]{3})$', degustbrowser.views.static, name='staticimg'),
    url(r'^'+ORGANISMUID+r'/'+DATASETUID+r'/(css/images/[-_a-z0-9]+.[pngif]{3})$', degustbrowser.views.static, name='staticcssimg'),

]

landing/urls.py
"""
Landing portal URL Configuration

NOTE: these urlpatterns are appended to end of master URLs so they are 
      effectively top-level URLs too.
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

import landing.views

from common.uid import ORGANISMUID, COLLECTIONUID, DATASETUID, SAMPLEUID, FEATUREUID

urlpatterns = [
    
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')?)$', landing.views.home, name='home'),
    
    # /[COLLECTIONUID/]dataset/ORGANISMUID/DATASETUID/SAMPLEUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')$', landing.views.datasetlist, name='datasetlist'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')$', landing.views.datasetdetails, name='datasetdetails'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')/(?P<sampleuid>'+SAMPLEUID+r')$', landing.views.sampledetails, name='sampledetails'),
    
    # /download/DATASETUID/FORMAT
    url(r'^download/('+DATASETUID+r')/([a-z]+)$', landing.views.datasetdownload, name='datasetdownload'),
    
    # /feature/DATASETUID/FEATUREUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?feature/(?P<datasetuid>'+DATASETUID+r')/(?P<featureuid>'+FEATUREUID+r')$', landing.views.datasetfeature, name='datasetfeature'),
    
    # /reference/REFERENCEUID[/FEATUREUID]
#     url(r'^reference$', landing.views.referencelist, name='referencelist'),
#     url(r'^reference/('+REFERENCEUID+r')$', landing.views.referencedetails, name='referencedetails'),
#     url(r'^reference/('+REFERENCEUID+r')/('+FEATUREUID+r')$', landing.views.referencegene, name='referencegene'),
    
    url(r'^help', RedirectView.as_view(url='https://docs.google.com/document/d/1o7IyQp02bsBW_FZDo6RFzSHD34aG_wJuhuvBYFv2GLc', permanent=False)),

]

degustbrowser/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

degustbrowser/views.py
import os
import sys
import logging

from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponse, Http404, HttpResponseForbidden
from django.shortcuts import render
from django.template.context_processors import csrf
from django.urls.base import reverse
from django_cgi_wrap import cgi_wrap

import common
from AgriBioHVC import settings
from common.bl.messagemanager import MessageManager
from common.bl.datamanager import DataManager
from landing.views import _parentList


def home(request, organismuid, datasetuid, collectionuid=None):
    '''Renders the Degust browser (home view) inside our template'''
    
    # load data objects
    mycollectionuid = collectionuid
    if not collectionuid:
        mycollectionuid = settings.DEFAULT_COLLECTION
    try:
        collection = common.models.Collection.objects.get(uid=mycollectionuid)
        organism = common.models.Species.objects.get(uid=organismuid, deleted__isnull=True)
        dataset = organism.dataset_set.get(uid=datasetuid, deleted__isnull=True)
    except ObjectDoesNotExist:
        raise Http404
    
    # check user is (not) allowed
    if not DataManager.canViewDataset(dataset, request.user):
        return HttpResponseForbidden()
    
    # otherwise allow the request
    params = {
              'request': request,
              'messages': MessageManager.getMessages(request),
              'group': 'efp',
              'parents': _parentList(collection, not collectionuid,
                  ('%s datasets' % organism.name, reverse('datasetlist', kwargs={'collectionuid': collectionuid, 'organismuid': organism.uid,})),
                  (dataset.name, reverse('datasetdetails', kwargs={'collectionuid': collectionuid, 'organismuid': organism.uid, 'datasetuid': dataset.uid,})),
              ),
              'page': settings.DEGUST_COMMON_NAME, 
              'children': [ ],
              'organism': organism,
              'dataset': dataset,
              'settings': settings,
              'title': '%s - %s'%(dataset.name,settings.DEGUST_COMMON_NAME),
              'collection': collection,
             }
    params.update(csrf(request))
    
    return render(request, "degust/home.html", params)


def compare(request, speciesuid, datasetuid):
    '''Renders the Degust browser (home view) inside our template'''
    
    # load data objects
    dataset = common.models.Dataset.objects.get(uid=request.GET.get('code'), deleted__isnull=True)
    species = dataset.species
    
    # check user is (not) allowed
    if not DataManager.canViewDataset(dataset, request.user):
        return HttpResponseForbidden()
    
    # otherwise allow the request
    params = {
              'request': request,
              'messages': MessageManager.getMessages(request),
              'group': 'efp',
              'parents': [
                  settings.HOME_LINK,
                  (settings.PORTAL_NAME, reverse('home')),
                  ('%s datasets' % species.name, reverse('datasetlist', args=(species.uid, ))),
                  (dataset.name, reverse('datasetdetails', args=(species.uid, dataset.uid))),
              ],
              'page': "Degust Browser", 
              'children': [ ],
              'species': species,
              'dataset': dataset,
              'settings': settings,
              'title': '',
             }
    params.update(csrf(request))
    
    return render(request, "degust/compare-plain.html", params)


def rjson(request, speciesuid, datasetuid):
    '''Runs r-json.cgi file for selected dataset'''
    
    # load data objects
    dataset = common.models.Dataset.objects.get(uid=request.GET.get('code'), deleted__isnull=True)
    
    # check user is (not) allowed
    if not DataManager.canViewDataset(dataset, request.user):
        return HttpResponseForbidden()
    
    # otherwise allow the request
    return cgi_wrap(request, 
                    os.path.join(settings.VIEWERSETTINGS['degust']['builddir'], 'r-json.cgi'),
                    cwd=settings.VIEWERSETTINGS['degust']['builddir'])


MIMEEXTS = {
    'js': 'text/javascript',
    'css': 'text/css',
    'png': 'image/png',
    'gif': 'image/gif',
    'jpg': 'image/jpeg',
    'html': 'text/html',
}

def static(request, filename):
    '''Serves static files'''
    
    ext = str(filename).split('.')[-1]
    
    if ext in MIMEEXTS:
        try:
            with open(os.path.join(settings.VIEWERSETTINGS['degust']['staticdirectory'], filename)) as f:
                return HttpResponse(f.read(), content_type=MIMEEXTS[ext])
        except:
            pass
        
    raise Http404

degustbrowser/templates/degust/compare-plain.html
<html>{% load static from staticfiles %}
  <head profile="http://www.w3.org/2005/10/profile">
    <link rel="icon" type="image/png" href="images/favicon.png"/>
    <title>Degust Browser - La Trobe University RNAseq Database</title>

    <!-- Externals CSS -->
    <link rel="stylesheet" href='./css/lib.css' />
    <link rel="stylesheet" href='./css/common.css' type="text/css" />
    <link rel="stylesheet" href='./css/compare.css' type="text/css "/>

    <script type="text/javascript" src='./common.js'></script>
    <script type="text/javascript" src='./slickgrid.js'></script>
    <script type="text/javascript" src='./compare.js'></script>
    
    <script type="text/javascript" src="{% static 'degust/iframeResizer.contentWindow.min.js' %}"></script>
  </head>
  <body>
    <div id="replace-me" class="container">
      <div class="jumbotron">
        <h1>Degust</h1>
        <p><a href='http://victorian-bioinformatics-consortium.github.io/degust/'>Degust</a> is preparing your data...  prepare for degustation...</p>
        <img src='./images/front-loader.gif'>
      </div>
    </div>

    <script type="text/javascript">
      window.settings = { };
    </script>
    <script type="text/javascript">
	    jQuery(document).ready(function () {
	        jQuery("#IDofControlFiringResizeEvent").click(function () {
	            var frame = $('#IDofiframeInMainWindow', window.parent.document);
	            var height = jQuery("#IDofContainerInsideiFrame").height();
	            frame.height(height + 15);
	        });
	        
	        // pre-filter Genes if q getvar is passed to parent window
			function getQueryVariable(variable)
			{
			       var query = parent.window.location.search.substring(1);
			       var vars = query.split("&");
			       for (var i=0;i<vars.length;i++) {
			               var pair = vars[i].split("=");
			               if(pair[0] == variable){return pair[1];}
			       }
			       return(false);
			}
			var q=getQueryVariable("q");
			if (q!=false) {
				setTimeout(function(){ jQuery('div.tab-search > input').val(q).trigger('keyup'); }, 500); // small delay as search box is created via javascript
			}
	    });
	</script>
  </body>
</html>

degustbrowser/templates/degust/compare.html
{% extends "_nostyle" %}

{% load messages %}
{% load dictutils %}
{% load static from staticfiles %}
{% load stringutils %}

{% block 'title' %}
	<title>Degust Browser - La Trobe University RNAseq Database</title>
{% endblock %}

{% block 'headercss' %}
    <link rel="stylesheet" href='./css/lib.css' />
    <link rel="stylesheet" href='./css/common.css' type="text/css" />
    <link rel="stylesheet" href='./css/compare.css' type="text/css "/>
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
{% endblock %}

{% block 'headerjs' %}
    <script type="text/javascript" src='./common.js'></script>
    <script type="text/javascript" src='./slickgrid.js'></script>
    <script type="text/javascript" src='./compare.js'></script>
{% endblock %} 

{% block 'content' %}
	<div id="replace-me" class="container">
		<div class="jumbotron">
			<h1>Degust</h1>
			<p>
				<a href='http://victorian-bioinformatics-consortium.github.io/degust/'>Degust</a>
				is preparing your data... prepare for degustation...
			</p>
			<img src='./images/front-loader.gif'>
		</div>
	</div>
{% endblock %}

{% block 'footerjs' %}
	<script type="text/javascript">
		window.settings = {};
	</script>
{% endblock %}

degustbrowser/templates/degust/home.html
{% extends collection.get_template %}

{% load landing %}
{% load messages %}
{% load dictutils %}
{% load static from staticfiles %}
{% load stringutils %}

{% block 'headerjs' %}
    <script type="text/javascript" src="{% static 'degust/iframeResizer.min.js' %}"></script>
{% endblock %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{settings.DEGUST_COMMON_NAME}}</h1>
	<div class="degust-description">{{dataset.degustdescription|markdown|safe}}</div>
	<iframe id="iframe" src="{% url 'degust:compare' organism.uid dataset.uid %}?code={{dataset.uid}}" style="width: 100%; border: 1px solid black;" scrolling="no"></iframe>
	<script>iFrameResize({log:true})</script>
	<p class="powered-by">Powered by <a href="https://drpowell.github.io/degust/" title="Open Degust developer page">Degust</a></p>
{% endblock %}