AgriBioHVC/urls.py
"""
AgriBioHVC (Top-level) URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin as djadmin
from django.views.generic.base import RedirectView

import common.views
import efpbrowser.urls
import degustbrowser.urls
#import geneview.urls
import landing.urls
import ptadmin.urls
import background.urls
from AgriBioHVC import settings

urlpatterns = [
    
    url(r'^efp/', include(efpbrowser.urls, namespace='efp')),
    url(r'^degust/', include(degustbrowser.urls, namespace='degust')),
    url(r'^portal-admin/', include(ptadmin.urls, namespace='ptadmin')),
    url(r'^portal-admin$', RedirectView.as_view(url='portal-admin/', permanent=False)),
    url(r'^background/', include(background.urls, namespace='background')),
    
    url(r'^django-admin/', djadmin.site.urls),
    url(r'^django-admin$', RedirectView.as_view(url='django-admin/', permanent=False)),
    
    url(r'^login', common.views.login_user, name='login'),
    url(r'^logout', common.views.logout_user, name='logout'),
    
    url(r'^content/([^/]*)', common.views.content, name='content'),
    url(settings.DATA_URL, common.views.data_server, name='content'),
    
    url(r'^status', common.views.status, name='status'),
]
urlpatterns.extend(landing.urls.urlpatterns)

landing/urls.py
"""
Landing portal URL Configuration

NOTE: these urlpatterns are appended to end of master URLs so they are 
      effectively top-level URLs too.
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

import landing.views

from common.uid import ORGANISMUID, COLLECTIONUID, DATASETUID, SAMPLEUID, FEATUREUID

urlpatterns = [
    
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')?)$', landing.views.home, name='home'),
    
    # /[COLLECTIONUID/]dataset/ORGANISMUID/DATASETUID/SAMPLEUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')$', landing.views.datasetlist, name='datasetlist'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')$', landing.views.datasetdetails, name='datasetdetails'),
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?dataset/(?P<organismuid>'+ORGANISMUID+r')/(?P<datasetuid>'+DATASETUID+r')/(?P<sampleuid>'+SAMPLEUID+r')$', landing.views.sampledetails, name='sampledetails'),
    
    # /download/DATASETUID/FORMAT
    url(r'^download/('+DATASETUID+r')/([a-z]+)$', landing.views.datasetdownload, name='datasetdownload'),
    
    # /feature/DATASETUID/FEATUREUID
    url(r'^(?:(?P<collectionuid>'+COLLECTIONUID+r')/)?feature/(?P<datasetuid>'+DATASETUID+r')/(?P<featureuid>'+FEATUREUID+r')$', landing.views.datasetfeature, name='datasetfeature'),
    
    # /reference/REFERENCEUID[/FEATUREUID]
#     url(r'^reference$', landing.views.referencelist, name='referencelist'),
#     url(r'^reference/('+REFERENCEUID+r')$', landing.views.referencedetails, name='referencedetails'),
#     url(r'^reference/('+REFERENCEUID+r')/('+FEATUREUID+r')$', landing.views.referencegene, name='referencegene'),
    
    url(r'^help', RedirectView.as_view(url='https://docs.google.com/document/d/1o7IyQp02bsBW_FZDo6RFzSHD34aG_wJuhuvBYFv2GLc', permanent=False)),

]

common/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Group
from django.utils import timezone

from common import modelfields



class Species(models.Model):
    '''Each species represented in database'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL.  e.g. barley')
    name = models.CharField(max_length=100, help_text='User pointing name for species.  e.g. Barley')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above data-set list on the Species landing page')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below data-set list on the Species landing page')
    
    # system fields
    public_dataset_count = models.IntegerField(default=0, help_text='Automatically updated by Dataset model.  Displayed on homepage')
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "Organism: %s [/%s]" % (self.name, self.uid)
    
    def references(self):
        return self.reference_set.filter(deleted__isnull=True)

REFERENCE_TYPE_CHOICES = (
    ('ge','Genome'),
    ('dg','Draft Genome'),
    ('tr','Transcriptome'),
    ('dt','Draft Transcriptome'),
    ('st','Self-assembled Transcriptome'),
)
REFERENCE_TYPE_LOOKUP = dict(REFERENCE_TYPE_CHOICES)

# REFERENCE_FEATURES_CHOICES = (
#     ('gene','Genes'),
#     ('tran','Transcripts'),
# )
# REFERENCE_FEATURES_LOOKUP = dict(REFERENCE_FEATURES_CHOICES)

class Reference(models.Model):
    '''A reference genome for a Species'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL and efp database table name.  e.g. barley')
    name = models.CharField(max_length=100, help_text='User pointing name for reference.  e.g. Barley')
    type = models.CharField(max_length=50, blank=True, help_text='Type of reference genome/transcriptome', choices=REFERENCE_TYPE_CHOICES)
    description = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text describing this reference e.g. where it was sourced, changes etc.')
    description_footer = models.TextField(null=True, blank=True, help_text='Extra Markdown/HTML formatted text describing this reference (below data-set list)')
    featurefile = models.CharField(max_length=56, blank=True, help_text='The name of the feature file (as saved in upload dir)', )
#     gfffeatures = modelfields.MultiCharField(max_length=20, blank=True, null=True, help_text='The types of features to include in reference', choices=REFERENCE_FEATURES_CHOICES)
    
    species = models.ForeignKey(Species)
    
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "Reference: %s [%s]" % (self.name, self.species.name)


class ReferenceFeature(models.Model):
    '''Transcript details for describing gene on landing page'''
     
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL and efp database table name.  e.g. barley')
    name = models.CharField(max_length=100, null=True, blank=True, help_text='User friendly name for feature if available')
    description = models.TextField(null=True, blank=True, help_text='Extra annotation for the gene/transcript/feature')
    
    reference = models.ForeignKey(Reference)
    
#     created = models.DateTimeField(auto_now_add=True)
#     modified = models.DateTimeField(auto_now=True)
#     deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")
    
    def __str__(self):
        if self.name:
            return "%s (%s)" % (self.name, self.uid)
        return self.uid


class Collection(models.Model):
    '''Group of data-sets'''
    
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL, file-system and database.  Restrict to [._a-zA-Z0-9].  e.g. smith2017')
    name = models.CharField(max_length=100, help_text='User pointing name for Collection.  e.g. AgriConnect, La Trobe etc.')
    name_short = models.CharField(max_length=50, null=True, blank=True, default=None, help_text='User pointing name used in breadcrumbs.  e.g. AgriConnect, La Trobe etc.')
    description_short = models.CharField(max_length=250, null=True, blank=True, help_text='Plain text formatted text for inclusion on home-page with collection link')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above data-sets')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below data-sets')

    template = models.ForeignKey('UpdateableTemplate', help_text='The template to use to draw landing page / viewers within')
    link_ltu = models.BooleanField(default=True, help_text='Link to the La Trobe pages in landing portal pages')
    link_top = models.BooleanField(default=True, help_text='Link to the top level landing portal page in landing portal pages, i.e. page selecting collection')
    link_collection = models.BooleanField(default=True, help_text='Include this collection on list of collections on landing home-page')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    deleted = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to delete this record.")

    def __str__(self):
        return "%s [/%s]" % (self.name, self.uid)
    
    def get_name_short(self):
        if self.name_short:
            return self.name_short
        return self.name
    def get_template(self):
        if self.template:
            return "UPDATEABLE_%s" % (self.template.name,)
        return None


COUNT_FORMAT_CHOICES = (
    ('RAW','Raw counts'),
    ('RPKM','RPKM/FPKM normalised counts'),
    ('TPM','TPM normalised counts'),
)
COUNT_FORMAT_LOOKUP = dict(COUNT_FORMAT_CHOICES)


class Dataset(models.Model):
    '''Each dataset represented in database'''
    
    class Meta:
        permissions = (
            ("can_view_any_dataset", "View Any Dataset"),
            ("can_edit_any_dataset", "Edit Any Dataset"),
        )
    
    # basic details
    uid = models.CharField(max_length=50, help_text='Unique identifier used in URL, file-system and database.  Restrict to [a-z0-9].  e.g. smith2017')
    name = models.CharField(max_length=100, help_text='User pointing name for Dataset.  e.g. Barley germination')
    description_header = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion above samples on data-set details')
    description_footer = models.TextField(null=True, blank=True, help_text='Markdown/HTML formatted text for inclusion below samples on data-set details')
    
    # file uploads
    countsfile = models.CharField(max_length=50, blank=True, help_text='The name of the counts file (as saved in upload dir)', )
    countsformat = models.CharField(max_length=5, blank=True, help_text='The type of counts in counts file', choices=COUNT_FORMAT_CHOICES)
    efphomeimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file used on homescreen i.e. without any expression. (as saved in upload dir)')
    efpexprimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file user to show expression (as saved in upload dir)')
    efpdownimage = models.CharField(max_length=50, blank=True, help_text='The name of the efpimage file user to show expression on download (as saved in upload dir)')
    countsdownload = models.BooleanField(default=False, blank=True, help_text='Check to allow users to download counts file')
    
    # detailed settings
    publish = models.DateTimeField(blank=True, null=True, help_text="Set the date/time to publish this dataset (publicly).  If in future it will automatically publish after this date.")
    labgroup = models.ForeignKey(Group, blank=True, null=True, help_text="The group of users who can access this dataset regardless if it's published")
    collections = models.ManyToManyField(Collection, blank=True, help_text='List of collections this data-set should be included in')
    metadata = models.TextField(blank=True, help_text='JSON formatted object representing the metadata of this dataset')
    
    externallinkurl = models.CharField(max_length=500, blank=True, help_text='URL to use for external link, GENEID is replaced with actual gene id', )
    externallinklabel = models.CharField(max_length=50, blank=True, help_text='Text label to use for external link, GENEID is replaced with actual gene id', )
    externallinkregex = models.CharField(max_length=100, blank=True, help_text='Regular expression used to select part of geneid to use in external link. e.g. remove transcript number', )
    externallinksub = models.CharField(max_length=50, blank=True, help_text='Substitution string used with regular expression e.g. remove transcript number', )
    
    species = models.ForeignKey(Species, blank=True, null=True, help_text='Organism of samples')
    reference = models.ForeignKey(Reference, default=None, blank=True, null=True, help_text='Reference used during mapping.  Data-set IDs must match reference IDs.')
    
    idcolumn = models.CharField(max_length=100, blank=True, null=True, help_text='The column in data-set which represents the gene/transcript ID.  This must match IDs used in reference.')

landing/templates/landing/datasetdetails.html
{% extends collection.get_template %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{dataset.name}}</h1>
	{% rendermessages messages %}
	
	{{dataset.description_header|markdown|safe}}
	
	{% if dataset.efpdeployed or dataset.degustdeployed %}<p><b>Viewers</b>: {% if dataset.efpdeployed %}
		<a href="{% url 'efp:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid %}" title="Open experiment in {{settings.EFP_COMMON_LINKNAME}}">[{{settings.EFP_COMMON_LINKNAME}}]</a>{% endif %}{% if dataset.degustdeployed %}
		<a href="{% url 'degust:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid %}" title="Open experiment in {{settings.DEGUST_COMMON_LINKNAME}}">[{{settings.DEGUST_COMMON_LINKNAME}}]</a>{% endif %}</p>{% endif %}{% if dataset.countsdownload %}
	<p><b>Download</b>: <a href="{% url 'datasetdownload' dataset.uid 'default' %}" title="Download full counts file in '{{dataset.countsformat}}' format">[{{dataset.countsformat}}]</a></p>{% endif %}	
	<p><b>Access</b>: {{dataset|publicprivate}}
	<h2>Samples</h2>{% for s in samples %}
	<h3><a href="{% url 'sampledetails'  collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid sampleuid=s.name %}">{{s.name}}</a></h3>
	<p>{{s.description|markdown|safe}}</p>
	{% empty %}
	<p>No samples available</p>
	{% endfor %}
	
	{{dataset.description_footer|markdown|safe}}
{% endblock %}

landing/templates/landing/datasetfeature.html
{% extends collection.get_template %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{title}}</h1>
	{% rendermessages messages %}
	<div><span class="keyword-name">Organism</span> <span class="keyword-value"><a href="{% url 'datasetlist' collectionuid=collection.uid organismuid=dataset.species.uid %}">{{dataset.species.name}}</a></span></div>
	<div><span class="keyword-name">Data-set</span> <span class="keyword-value"><a href="{% url 'datasetdetails' collectionuid=collection.uid organismuid=dataset.species.uid datasetuid=dataset.uid %}">{{dataset.name}}</a></span></div>
	{% if dataset.efpdeployed or dataset.degustdeployed %}<div><span class="keyword-name">Viewers</span> {% if dataset.efpdeployed %}
	<span class="keyword-value"><a href="{% url 'efp:home' collectionuid=collection.uid organismuid=dataset.species.uid datasetuid=dataset.uid %}?primaryGene={{feature.uid}}" title="Open feature in {{settings.EFP_COMMON_NAME}}">[{{settings.EFP_COMMON_NAME}}]</a></span>{% endif %}{% if dataset.degustdeployed %}
	<span class="keyword-value"><a href="{% url 'degust:home' collectionuid=collection.uid organismuid=dataset.species.uid datasetuid=dataset.uid %}?q={{feature.uid}}" title="Open feature in {{settings.DEGUST_COMMON_NAME}}">[{{settings.DEGUST_COMMON_NAME}}]</a></span>{% endif %}</div>{% endif %}
	{% if extlink.url %}<div><span class="keyword-name">External Links</span> <a href="{{extlink.url}}" title="Open feature in {{extlink.label}}">[{{extlink.label}}]</a></div>{% endif %}
	<h2>Feature Details</h2>
	<p>{% if feature.description %}{{feature.description}}{% else %}Unannotated feature{% endif %}</p>
	<h2>Data-set Details</h2>
	{{dataset.description_header|markdown|safe}}
	{{dataset.description_footer|markdown|safe}}
{% endblock %}

landing/templates/landing/datasetlisting.html
{% extends collection.get_template %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{organism.name}} dataset(s)</h1>
	{% rendermessages messages %}
	
	{{organism.description_header|markdown|safe}}
	
	<ul class="dataset-list">{% for d in datasets %}
		<li>
			<a href="{% url 'datasetdetails' collectionuid=collection.uid organismuid=organism.uid datasetuid=d.uid %}">{{d.name}}</a> ({{d.sample_set.count}} sample(s)) [{{d|publicprivate}}]
			<ul>{% if d.efpdeployed %}
				<li><a href="{% url 'efp:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=d.uid %}">{{settings.EFP_COMMON_LINKNAME}}</a></li>{% endif %}{% if d.degustdeployed %}
				<li><a href="{% url 'degust:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=d.uid %}">{{settings.DEGUST_COMMON_LINKNAME}}</a></li>{% endif %}{% if d.countsdownload %}
				<li><a href="{% url 'datasetdownload' d.uid 'default' %}" title="Download full counts file in {{d.countsformat}} format">Download ({{d.countsformat}})</a></li>{% endif %}
			</ul>
		</li>{% empty %}No {{organism.name}} datasets yet{% endfor %}
	</ul>
	
	{{organism.description_footer|markdown|safe}}
{% endblock %}

landing/templates/landing/home.html
{% extends collection.get_template %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{collection.name}}</h1>
	{% rendermessages messages %}
	
	{{collection.description_header|markdown|safe}}
	
	<h2>Organisms</h2>
	<ul class="species-list">{% for o in organism %}
		<li><a href="{% url 'datasetlist' collectionuid=collection.uid organismuid=o.uid %}">{{o.name}}</a> [{{o.dataset_set|in_collection:collection|notdeleted|accessible:request.user}}]</li>{% empty %}No organisms in database yet{% endfor %}
	</ul>
	
	{{collection.description_footer|markdown|safe}}{% if collection.link_top and collections %}
	
	<h2>Collections</h2>
	
	Alternatively you can view datasets from our other collections
	
	<ul class="collection">{% for c in collections %}
		<li>
			<div class="title"><a href="{% url 'home' collectionuid=c.uid %}">{{c.name}}</a>{% if c == collection %} [current]{% endif %}</div>
			<div class="description">{{c.description_short}}</div>
		</li>{% endfor %}
	</ul>{% endif %}
{% endblock %}

landing/templates/landing/referencedetails.html
{% extends 'UPDATEABLE_ltu' %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{reference.name}}</h1>
	{% rendermessages messages %}
	
	{{reference.description|markdown|safe}}
	
	{% if dataset.efpdeployed or dataset.degustdeployed %}<p><b>Viewers</b>: {% if dataset.efpdeployed %}
		<a href="{% url 'efp:home' species.uid dataset.uid %}" title="Open experiment in eFP Browser">[eFP]</a>{% endif %}{% if dataset.degustdeployed %}
		<a href="{% url 'degust:home' species.uid dataset.uid %}" title="Open experiment in Degust Browser">[Degust]</a>{% endif %}</p>{% endif %}
	
	<h2>Data-sets</h2><ul>{% for d in datasets %}
	<li><p><b><a href="{% url 'datasetdetails' d.species.uid d.uid %}">{{d.name}}</a></b> [{{d|publicprivate}}]</p>
	{{d.description|markdown|safe}}</li>
	{% empty %}
	<p>No data-sets available</p>
	{% endfor %}</ul>
	
	{{reference.description_footer|markdown|safe}}
{% endblock %}

landing/templates/landing/referencegene.html
{% extends 'UPDATEABLE_ltu' %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{reference.name}}: {% if feature.name %}{{feature.name}} ({{feature.uid}}){% else %}{{feature.uid}}{% endif %}</h1>
	{% rendermessages messages %}
	
	<div>{{feature.description}}</div>
	
	{% if dataset.efpdeployed or dataset.degustdeployed %}<p><b>Viewers</b>: {% if dataset.efpdeployed %}
		<a href="{% url 'efp:home' species.uid dataset.uid %}" title="Open feature in eFP Browser">[eFP]</a>{% endif %}{% if dataset.degustdeployed %}
		<a href="{% url 'degust:home' species.uid dataset.uid %}" title="Open feature in Degust Browser">[Degust]</a>{% endif %}</p>{% endif %}
	
	<h2>Data-sets</h2><ul>{% for d in datasets %}
	<li><p><b><a href="{% url 'datasetdetails' d.species.uid d.uid %}">{{d.name}}</a></b> [{{d|publicprivate}}]</p>
	{{d.description|markdown|safe}}</li>
	{% empty %}
	<p>No data-sets available</p>
	{% endfor %}</ul>
	
	{{reference.description_footer|markdown|safe}}
{% endblock %}

landing/templates/landing/referencelist.html
{% extends 'UPDATEABLE_ltu' %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>References</h1>
	{% rendermessages messages %}
	{% for s in species %}{% if s.reference_set|notdeleted|count > 0 %}
	<h2>{{s.name}}</h2>
	<ul class="reference-list">{% for r in s.reference_set|notdeleted %}
		<li><a href="{% url 'referencedetails' r.uid %}">{{r.name}}</a> [{{r.dataset_set|accessible:request.user}}]</li>{% empty %}No {{s.name}} references yet{% endfor %}
	</ul>{% endif %}{% endfor %}
{% endblock %}

landing/templates/landing/sampledetails.html
{% extends collection.get_template %}

{% load static from staticfiles %}
{% load messages %}
{% load landing %}

{% block 'headercss' %}
	<link rel="stylesheet" href="{% static 'common/alert.css' %}" />
	<link rel="stylesheet" href="{% static 'common/base.css' %}" />
	<link rel="stylesheet" href="{% static 'landing/css/base.css' %}" />
{% endblock %}

{% block 'content' %}
	<h1>{{dataset.name}}: {{sample.name}}</h1>
	{% rendermessages messages %}
	<div><span class="keyword-name">Organism</span> <span class="keyword-value"><a href="{% url 'datasetlist' collectionuid=collection.uid organismuid=organism.uid %}">{{organism.name}}</a></span></div>
	<div><span class="keyword-name">Data-set</span> <span class="keyword-value"><a href="{% url 'datasetdetails' collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid %}">{{dataset.name}}</a></span></div>
	<h2>Sample Details</h2>
	<p>{{sample.description|markdown|safe}}</p>
	{% if dataset.efpdeployed or dataset.degustdeployed %}<p><strong>Viewers</strong>: {% if dataset.efpdeployed %}
	<a href="{% url 'efp:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid %}" title="Open experiment in {{settings.EFP_COMMON_NAME}}">[{{settings.EFP_COMMON_NAME}}]</a>{% endif %}{% if dataset.degustdeployed %}
	<a href="{% url 'degust:home' collectionuid=collection.uid organismuid=organism.uid datasetuid=dataset.uid %}" title="Open experiment in {{settings.DEGUST_COMMON_NAME}}">[{{settings.DEGUST_COMMON_NAME}}]</a>{% endif %}</p>{% endif %}
	<h2>Data-set Details</h2>
	{{dataset.description_header|markdown|safe}}
	{{dataset.description_footer|markdown|safe}}
{% endblock %}